### ISSUE TITLE
Icon w/ label shown?

### ISSUE THREAD

**Issue by SteveTheTechie** [tyleryasaka/inlinesave#12]
It would be helpful if there was an option to show the save and cancel icons w/ labels or just show the labels.   My concern is that my users will not recognize the checkmark as a save button.  If you needed a different icon for this, you could just do the filename switch with a ternary expression that keys off a config option.

**Comment by tyleryasaka** [comment]
Yeah I like that idea. I had wondered if the icons made the functionality clear. Also as a side note, I don't know if the current icons are the best as far as matching the style of the other CKEditor icons.
Is this something you want to implement? If not I can work on it when I get a chance. But I'm not exactly sure what you meant by the last part, or exactly what sort of label you have in mind. (I don't currently use CKEditor in anything so maybe I'm just not familiar with labeling options.)

**Comment by SteveTheTechie** [comment]
I would suggest loading the Source Dialog plug-in and taking a look at how they do the icon+label for the button.  It is a good example.  Regarding the ternary (a ? b : c), see below:
(I need to focus on other things now.)

```
    editor.ui.addButton( 'Inlinesave',
    {
        label: 'Save',
        command: 'inlinesave',
        icon: this.path + (config.inlinesave.showLabel ? 'images/inlinesavelabel.png' : 'images/inlinesave.png')
    } );
```

**Comment by tyleryasaka** [comment]
Thanks, I see now. Ok I'll work on this when I get a chance.

**Comment by tyleryasaka** [comment]
Turns out the labels are already there for each icon - they're just set to `display: none`. So I added instructions to the readme to display the labels.

I also changed the icons to better match the other ckeditor icons.

**Comment by SteveTheTechie** [comment]
Awesome!
