### ISSUE TITLE
Plugin sends POST and GET requests on Save click

### ISSUE THREAD

**Issue by mayos** [tyleryasaka/inlinesave#13]
Hello all,

The subj.

On the server I see that plugin sends POST and GET queries at the same time, so the sample functions logs the full page code (as it requested by GET) in the console, did you meet this?

Thanks in advance.

**Comment by tyleryasaka** [comment]
@mayos No I am not able to reproduce this issue. The plugin should only be sending a POST request when the save button is clicked.

Now if you are using this along with the `notification` plugin, the first time you click the 'save' button, a notification will popup. CKEditor's notification uses an image for the 'close' icon, which will be loaded via GET the first time it appears. Just a guess, but perhaps this is what you are seeing.
