### ISSUE TITLE
color icons

### ISSUE THREAD

**Issue by SteveTheTechie** [tyleryasaka/inlinesave#14]
Any chance I can persuade to you upload additional color icons that we can optionally choose to use?  (e.g., just leave the current mono ones as default)

I liked the colors of the original ones (green and red), I just thought the check mark was confusing.

**Comment by tyleryasaka** [comment]
Sure. The current images are just SVGs so changing the color will be easy.
I'll do this when I get a chance.

**Comment by tyleryasaka** [comment]
I added optional color icons, explained in the readme. See what you think. @SteveTheTechie

**Comment by tyleryasaka** [comment]
Changes are live.
