### ISSUE TITLE
onSave cancel event

### ISSUE THREAD

**Issue by marc-gist** [tyleryasaka/inlinesave#17]
I want to do some checks before making the AJAX call; is there a way to stop the ajax call in the onSave method?

Thanks,

**Comment by tyleryasaka** [comment]
@marc-gist currently there is not a way to do this, but that would be a good feature to have. I will take a look and put something in place for that when I get a chance (I am quite busy now so bear with me). Or if you feel like implementing it yourself you are always welcome to contribute.

**Comment by marc-gist** [comment]
created a pull request. used return from onSave to set a variable that will control if we send the data or not.  thanks for encouraging me to make changes myself!

**Comment by tyleryasaka** [comment]
Awesome, thanks! I'll take a look soon.

**Comment by tyleryasaka** [comment]
@marc-gist just merged your pull request. Made a couple of formatting tweaks just for consistency. I also updated the documentation to reflect your changes.

I'll give this a day or two to make sure nothing else comes up, and then I will update the code on ckeditor.com.

**Comment by tyleryasaka** [comment]
Changes have been made live. I'll close this now.
