### ISSUE TITLE
unable to send latest changed content in postData

### ISSUE THREAD

**Issue by rohankhudedev** [tyleryasaka/inlinesave#26]
My Code:
```
config.inlinesave = {
        postUrl: '/inline-update',
        postData: {
            text: this.getData(),
        },
        onSave: function( editor ) {
            console.log( 'clicked save', editor );
            return true;
        },
        onSuccess: function( editor, data ) {
            console.log( 'save successful', editor, data );
        },
        onFailure: function( editor, status, request ) {
            console.log( 'save failed', editor, status, request );
        },
        successMessage: 'Yay we saved it!',
        errorMessage: 'Something went wrong :(',
        useJSON: false,
        useColorIcon: false
    };
```
i want to send full content of editable div to server. so using `text: this.getData(),` in `postData`. But its not sending latest changed content.
Any help will be appreciated.

**Comment by rohankhudedev** [comment]
i have also tried using `editabledata`, but it strips some HTML tags. were i needed full latest changed data from editable div.

**Comment by rohankhudedev** [comment]
Solved!!!
ckeditor itself strips some HTML tags onload. So to disable this i added below line in `config.js`
`config.allowedContent = true;`

Now by using `editabledata`, i can access updated data from editable div with all HTML elements.

Sorry, this issue is of ckeditor.

Thank you so much.

**Comment by rohankhudedev** [comment]
Solved!!!
ckeditor itself strips some HTML tags onload. So to disable this i added below line in `config.js`
`config.allowedContent = true;`

Now by using `editabledata`, i can access updated data from editable div with all HTML elements.

Sorry, this issue is of ckeditor.

Thank you so much.

**Comment by tyleryasaka** [comment]
Glad you got it figured out!
