### ISSUE TITLE
Minified files

### ISSUE THREAD

**Issue by SteveTheTechie** [tyleryasaka/inlinesave#9]
I would recommend creating some src sub folders under inlinesave and inlinecancel and putting the current unminified plugin.js files there.  Put minified/obfuscated versions of those files in the parent inlinesave and inlinecancel folders.  Of course, the intention is that developers would actually use the minified versions, while still having access to the unminified js files in the src subfolders to suggest updates for.

This would be a bit more work for you to keep the unminified and minified versions in sync, but I think people will appreciate that you even have minified/obfuscated versions for use.  (Also, don't expect people to upload updated minified versions... they will probably just suggest updated to the unminified src only.)

_A pet peeve of mine is that CKEditor plugins are seldom minified.  It may seem inconsequential when they are small files...  However, if you are using a lot of plugins like I am, all the little impacts add up and slow down the editor loading._

**Comment by tyleryasaka** [comment]
Yeah, never thought about minifying them since they're so small, but I see your point. Done.
